unit Photos_SQLite_iOS;

interface

uses
  Columns, DataStorage, SysUtils;

function GetTable(const Name : string) : TSQL_Table_array;

implementation

function GetTable(const Name : string) : TSQL_Table_array;
const

  // DO NOT TRANSLATE SQL_COL. TRANSLATE ONLY FEX_COL.
  // MAKE SURE COL DOES NOT ALREADY EXIST AS A DIFFERENT TYPE.
  // ROW ORDER IS PROCESS ORDER
  // DO NOT USE RESERVED NAMES IN FEX_COL LIKE 'NAME', 'ID'

  Array_Items_PHOTOS_SQLITE_IOS: TSQL_Table_array = (
   (sql_col: 'DNT_ZADDEDDATE';                               fex_col: 'ZADDEDDATE';                                    read_as: ftLargeInt;      convert_as: 'ABS';        col_type: ftDateTime;     show: True),
   (sql_col: 'DNT_ZDATECREATED';                             fex_col: 'ZDATECREATED';                                  read_as: ftLargeInt;      convert_as: 'ABS';        col_type: ftDateTime;     show: True),
   (sql_col: 'DNT_ZMODIFICATIONDATE';                        fex_col: 'ZMODIFICATIONDATE';                             read_as: ftLargeInt;      convert_as: 'ABS';        col_type: ftDateTime;     show: True),
   (sql_col: 'DNT_ZDIRECTORY';                               fex_col: 'ZDIRECTORY';                                    read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
   (sql_col: 'DNT_ZFILENAME';                                fex_col: 'ZFILENAME';                                     read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
   (sql_col: 'DNT_ZLATITUDE';                                fex_col: 'ZLATITUDE';                                     read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
   (sql_col: 'DNT_ZLONGITUDE';                               fex_col: 'ZLONGITUDE';                                    read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
   (sql_col: 'DNT_ZDURATION';                                fex_col: 'ZDURATION';                                     read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
   (sql_col: 'DNT_ZHIDDEN';                                  fex_col: 'ZHIDDEN';                                       read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
   (sql_col: 'DNT_ZORIENTATION';                             fex_col: 'ZORIENTATION';                                  read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
   (sql_col: 'DNT_ZKIND';                                    fex_col: 'ZKIND';                                         read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
   (sql_col: 'DNT_ZKINDSUBTYPE';                             fex_col: 'ZKINDSUBTYPE';                                  read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
   (sql_col: 'DNT_ZCLOUDDELETESTATE';                        fex_col: 'ZCLOUDDELETESTATE';                             read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
   (sql_col: 'DNT_ZFAVORITE';                                fex_col: 'ZFAVORITE';                                     read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
   (sql_col: 'DNT_ZTRASHEDSTATE';                            fex_col: 'ZTRASHEDSTATE';                                 read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ACHANGE';                                  fex_col: 'ACHANGE';                                       read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ATRANSACTION';                             fex_col: 'ATRANSACTION';                                  read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ATRANSACTIONSTRING';                       fex_col: 'ATRANSACTIONSTRING';                            read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_17CLUSTERREJECTEDPERSONS';               fex_col: 'Z_17CLUSTERREJECTEDPERSONS';                    read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_17REJECTEDPERSONS';                      fex_col: 'Z_17REJECTEDPERSONS';                           read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_17REJECTEDPERSONSNEEDINGFACECROPS';      fex_col: 'Z_17REJECTEDPERSONSNEEDINGFACECROPS';           read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_1KEYWORDS';                              fex_col: 'Z_1KEYWORDS';                                   read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_25ALBUMLISTS';                           fex_col: 'Z_25ALBUMLISTS';                                read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_26ASSETS';                               fex_col: 'Z_26ASSETS';                                    read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_3MEMORIESBEINGCURATEDASSETS';            fex_col: 'Z_3MEMORIESBEINGCURATEDASSETS';                 read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_3MEMORIESBEINGEXTENDEDCURATEDASSETS';    fex_col: 'Z_3MEMORIESBEINGEXTENDEDCURATEDASSETS';         read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_3MEMORIESBEINGMOVIECURATEDASSETS';       fex_col: 'Z_3MEMORIESBEINGMOVIECURATEDASSETS';            read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_3MEMORIESBEINGREPRESENTATIVEASSETS';     fex_col: 'Z_3MEMORIESBEINGREPRESENTATIVEASSETS';          read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_3SUGGESTIONSBEINGKEYASSETS';             fex_col: 'Z_3SUGGESTIONSBEINGKEYASSETS';                  read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_3SUGGESTIONSBEINGREPRESENTATIVEASSETS';  fex_col: 'Z_3SUGGESTIONSBEINGREPRESENTATIVEASSETS';       read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_44INVALIDMERGECANDIDATES';               fex_col: 'Z_44INVALIDMERGECANDIDATES';                    read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_44MERGECANDIDATES';                      fex_col: 'Z_44MERGECANDIDATES';                           read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_ENT';                                    fex_col: 'Z_ENT';                                         read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_FOK_CLOUDFEEDASSETSENTRY';               fex_col: 'Z_FOK_CLOUDFEEDASSETSENTRY';                    read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_METADATA';                               fex_col: 'Z_METADATA';                                    read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_MODELCACHE';                             fex_col: 'Z_MODELCACHE';                                  read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_OPT';                                    fex_col: 'Z_OPT';                                         read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_PK';                                     fex_col: 'Z_PK';                                          read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_PRIMARYKEY';                             fex_col: 'Z_PRIMARYKEY';                                  read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_RT_Asset_boundedByRect';                 fex_col: 'Z_RT_Asset_boundedByRect';                      read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_RT_Asset_boundedByRect_node';            fex_col: 'Z_RT_Asset_boundedByRect_node';                 read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_RT_Asset_boundedByRect_parent';          fex_col: 'Z_RT_Asset_boundedByRect_parent';               read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_Z_RT_Asset_boundedByRect_rowid';           fex_col: 'Z_RT_Asset_boundedByRect_rowid';                read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZADDITIONALASSETATTRIBUTES';               fex_col: 'ZADDITIONALASSETATTRIBUTES';                    read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZADDITIONALATTRIBUTES';                    fex_col: 'ZADDITIONALATTRIBUTES';                         read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZADJUSTMENTTIMESTAMP';                     fex_col: 'ZADJUSTMENTTIMESTAMP';                          read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZALBUMLIST';                               fex_col: 'ZALBUMLIST';                                    read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZANALYSISSTATEMODIFICATIONDATE';           fex_col: 'ZANALYSISSTATEMODIFICATIONDATE';                read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZASSET';                                   fex_col: 'ZASSET';                                        read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZASSETANALYSISSTATE';                      fex_col: 'ZASSETANALYSISSTATE';                           read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZASSETDESCRIPTION';                        fex_col: 'ZASSETDESCRIPTION';                             read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZAVALANCHEPICKTYPE';                       fex_col: 'ZAVALANCHEPICKTYPE';                            read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZAVALANCHEUUID';                           fex_col: 'ZAVALANCHEUUID';                                read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCAMERAPROCESSINGADJUSTMENTSTATE';         fex_col: 'ZCAMERAPROCESSINGADJUSTMENTSTATE';              read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDASSETGUID';                          fex_col: 'ZCLOUDASSETGUID';                               read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDBATCHID';                            fex_col: 'ZCLOUDBATCHID';                                 read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDBATCHPUBLISHDATE';                   fex_col: 'ZCLOUDBATCHPUBLISHDATE';                        read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDCOLLECTIONGUID';                     fex_col: 'ZCLOUDCOLLECTIONGUID';                          read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDDOWNLOADREQUESTS';                   fex_col: 'ZCLOUDDOWNLOADREQUESTS';                        read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDFEEDASSETSENTRY';                    fex_col: 'ZCLOUDFEEDASSETSENTRY';                         read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDFEEDENTRY';                          fex_col: 'ZCLOUDFEEDENTRY';                               read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDHASCOMMENTSBYME';                    fex_col: 'ZCLOUDHASCOMMENTSBYME';                         read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDHASCOMMENTSCONVERSATION';            fex_col: 'ZCLOUDHASCOMMENTSCONVERSATION';                 read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDHASUNSEENCOMMENTS';                  fex_col: 'ZCLOUDHASUNSEENCOMMENTS';                       read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDISDELETABLE';                        fex_col: 'ZCLOUDISDELETABLE';                             read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDISMYASSET';                          fex_col: 'ZCLOUDISMYASSET';                               read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDLASTVIEWEDCOMMENTDATE';              fex_col: 'ZCLOUDLASTVIEWEDCOMMENTDATE';                   read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDLOCALSTATE';                         fex_col: 'ZCLOUDLOCALSTATE';                              read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDMASTER';                             fex_col: 'ZCLOUDMASTER';                                  read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDMASTERMEDIAMETADATA';                fex_col: 'ZCLOUDMASTERMEDIAMETADATA';                     read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDOWNERHASHEDPERSONID';                fex_col: 'ZCLOUDOWNERHASHEDPERSONID';                     read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDPLACEHOLDERKIND';                    fex_col: 'ZCLOUDPLACEHOLDERKIND';                         read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDRESOURCE';                           fex_col: 'ZCLOUDRESOURCE';                                read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDSERVERPUBLISHDATE';                  fex_col: 'ZCLOUDSERVERPUBLISHDATE';                       read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDSHAREDALBUMINVITATIONRECORD';        fex_col: 'ZCLOUDSHAREDALBUMINVITATIONRECORD';             read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCLOUDSHAREDCOMMENT';                      fex_col: 'ZCLOUDSHAREDCOMMENT';                           read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCODEC';                                   fex_col: 'ZCODEC';                                        read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCOMPLETE';                                fex_col: 'ZCOMPLETE';                                     read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCOMPUTEDASSETATTRIBUTES';                 fex_col: 'ZCOMPUTEDASSETATTRIBUTES';                      read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCOMPUTEDATTRIBUTES';                      fex_col: 'ZCOMPUTEDATTRIBUTES';                           read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCURATIONSCORE';                           fex_col: 'ZCURATIONSCORE';                                read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZCUSTOMRENDEREDVALUE';                     fex_col: 'ZCUSTOMRENDEREDVALUE';                          read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZDAYGROUPHIGHLIGHTBEINGASSETS';            fex_col: 'ZDAYGROUPHIGHLIGHTBEINGASSETS';                 read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZDAYGROUPHIGHLIGHTBEINGEXTENDEDASSETS';    fex_col: 'ZDAYGROUPHIGHLIGHTBEINGEXTENDEDASSETS';         read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZDAYGROUPHIGHLIGHTBEINGKEYASSET';          fex_col: 'ZDAYGROUPHIGHLIGHTBEINGKEYASSET';               read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZDAYGROUPHIGHLIGHTBEINGSUMMARYASSETS';     fex_col: 'ZDAYGROUPHIGHLIGHTBEINGSUMMARYASSETS';          read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZDEFERREDPROCESSINGNEEDED';                fex_col: 'ZDEFERREDPROCESSINGNEEDED';                     read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZDEFERREDREBUILDFACE';                     fex_col: 'ZDEFERREDREBUILDFACE';                          read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZDEPTHTYPE';                               fex_col: 'ZDEPTHTYPE';                                    read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZDERIVEDCAMERACAPTUREDEVICE';              fex_col: 'ZDERIVEDCAMERACAPTUREDEVICE';                   read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZDETECTEDFACE';                            fex_col: 'ZDETECTEDFACE';                                 read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZDETECTEDFACEGROUP';                       fex_col: 'ZDETECTEDFACEGROUP';                            read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZDETECTEDFACEPRINT';                       fex_col: 'ZDETECTEDFACEPRINT';                            read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZEDITEDIPTCATTRIBUTES';                    fex_col: 'ZEDITEDIPTCATTRIBUTES';                         read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZEXTENDEDATTRIBUTES';                      fex_col: 'ZEXTENDEDATTRIBUTES';                           read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZFACEADJUSTMENTVERSION';                   fex_col: 'ZFACEADJUSTMENTVERSION';                        read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZFACEAREAPOINTS';                          fex_col: 'ZFACEAREAPOINTS';                               read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZFACECROP';                                fex_col: 'ZFACECROP';                                     read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZFILESYSTEMBOOKMARK';                      fex_col: 'ZFILESYSTEMBOOKMARK';                           read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZFILESYSTEMVOLUME';                        fex_col: 'ZFILESYSTEMVOLUME';                             read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZGENERICALBUM';                            fex_col: 'ZGENERICALBUM';                                 read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZGLOBALKEYVALUE';                          fex_col: 'ZGLOBALKEYVALUE';                               read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZGROUPINGSTATE';                           fex_col: 'ZGROUPINGSTATE';                                read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZGROUPINGUUID';                            fex_col: 'ZGROUPINGUUID';                                 read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZHASADJUSTMENTS';                          fex_col: 'ZHASADJUSTMENTS';                               read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZHDRGAIN';                                 fex_col: 'ZHDRGAIN';                                      read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZHEIGHT';                                  fex_col: 'ZHEIGHT';                                       read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZHIGHFRAMERATESTATE';                      fex_col: 'ZHIGHFRAMERATESTATE';                           read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZHIGHLIGHTBEINGASSETS';                    fex_col: 'ZHIGHLIGHTBEINGASSETS';                         read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZHIGHLIGHTBEINGEXTENDEDASSETS';            fex_col: 'ZHIGHLIGHTBEINGEXTENDEDASSETS';                 read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZHIGHLIGHTBEINGKEYASSET';                  fex_col: 'ZHIGHLIGHTBEINGKEYASSET';                       read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZHIGHLIGHTBEINGSUMMARYASSETS';             fex_col: 'ZHIGHLIGHTBEINGSUMMARYASSETS';                  read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZHIGHLIGHTVISIBILITYSCORE';                fex_col: 'ZHIGHLIGHTVISIBILITYSCORE';                     read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZIMAGEREQUESTHINTS';                       fex_col: 'ZIMAGEREQUESTHINTS';                            read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZIMPORTSESSION';                           fex_col: 'ZIMPORTSESSION';                                read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZINTERNALRESOURCE';                        fex_col: 'ZINTERNALRESOURCE';                             read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZKEYWORD';                                 fex_col: 'ZKEYWORD';                                      read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZLASTSHAREDDATE';                          fex_col: 'ZLASTSHAREDDATE';                               read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZLEGACYFACE';                              fex_col: 'ZLEGACYFACE';                                   read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZLIBRARYSCOPE';                            fex_col: 'ZLIBRARYSCOPE';                                 read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZLIBRARYSCOPEORIGINATOR';                  fex_col: 'ZLIBRARYSCOPEORIGINATOR';                       read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZLIMITEDLIBRARYFETCHFILTER';               fex_col: 'ZLIMITEDLIBRARYFETCHFILTER';                    read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZLOCALRESOURCESSTATE';                     fex_col: 'ZLOCALRESOURCESSTATE';                          read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZLOCATIONDATA';                            fex_col: 'ZLOCATIONDATA';                                 read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZMASTER';                                  fex_col: 'ZMASTER';                                       read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZMEDIAANALYSISASSETATTRIBUTES';            fex_col: 'ZMEDIAANALYSISASSETATTRIBUTES';                 read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZMEDIAANALYSISATTRIBUTES';                 fex_col: 'ZMEDIAANALYSISATTRIBUTES';                      read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZMEDIAGROUPUUID';                          fex_col: 'ZMEDIAGROUPUUID';                               read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZMEMORY';                                  fex_col: 'ZMEMORY';                                       read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZMIGRATIONHISTORY';                        fex_col: 'ZMIGRATIONHISTORY';                             read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZMOMENT';                                  fex_col: 'ZMOMENT';                                       read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZMOMENTLIST';                              fex_col: 'ZMOMENTLIST';                                   read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZMOMENTSHARE';                             fex_col: 'ZMOMENTSHARE';                                  read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZMONTHHIGHLIGHTBEINGFIRSTASSET';           fex_col: 'ZMONTHHIGHLIGHTBEINGFIRSTASSET';                read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZMONTHHIGHLIGHTBEINGKEYASSET';             fex_col: 'ZMONTHHIGHLIGHTBEINGKEYASSET';                  read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZORIGINALCOLORSPACE';                      fex_col: 'ZORIGINALCOLORSPACE';                           read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZOVERALLAESTHETICSCORE';                   fex_col: 'ZOVERALLAESTHETICSCORE';                        read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZPACKEDACCEPTABLECROPRECT';                fex_col: 'ZPACKEDACCEPTABLECROPRECT';                     read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZPACKEDBADGEATTRIBUTES';                   fex_col: 'ZPACKEDBADGEATTRIBUTES';                        read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZPACKEDPREFERREDCROPRECT';                 fex_col: 'ZPACKEDPREFERREDCROPRECT';                      read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZPERSON';                                  fex_col: 'ZPERSON';                                       read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZPERSONREFERENCE';                         fex_col: 'ZPERSONREFERENCE';                              read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZPHOTOSHIGHLIGHT';                         fex_col: 'ZPHOTOSHIGHLIGHT';                              read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZPLAYBACKSTYLE';                           fex_col: 'ZPLAYBACKSTYLE';                                read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZPLAYBACKVARIATION';                       fex_col: 'ZPLAYBACKVARIATION';                            read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZPROMOTIONSCORE';                          fex_col: 'ZPROMOTIONSCORE';                               read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZQUESTION';                                fex_col: 'ZQUESTION';                                     read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZSAVEDASSETTYPE';                          fex_col: 'ZSAVEDASSETTYPE';                               read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZSCENECLASSIFICATION';                     fex_col: 'ZSCENECLASSIFICATION';                          read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZSCENEPRINT';                              fex_col: 'ZSCENEPRINT';                                   read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZSEARCHDATA';                              fex_col: 'ZSEARCHDATA';                                   read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZSHARE';                                   fex_col: 'ZSHARE';                                        read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZSHAREPARTICIPANT';                        fex_col: 'ZSHAREPARTICIPANT';                             read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZSORTTOKEN';                               fex_col: 'ZSORTTOKEN';                                    read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZSOURCEASSETFORDUPLICATION';               fex_col: 'ZSOURCEASSETFORDUPLICATION';                    read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZSUGGESTION';                              fex_col: 'ZSUGGESTION';                                   read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZTHUMBNAILINDEX';                          fex_col: 'ZTHUMBNAILINDEX';                               read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZTRASHEDDATE';                             fex_col: 'ZTRASHEDDATE';                                  read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZUNIFORMTYPEIDENTIFIER';                   fex_col: 'ZUNIFORMTYPEIDENTIFIER';                        read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZUNMANAGEDADJUSTMENT';                     fex_col: 'ZUNMANAGEDADJUSTMENT';                          read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZUUID';                                    fex_col: 'ZUUID';                                         read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZVIDEOCPDURATIONVALUE';                    fex_col: 'ZVIDEOCPDURATIONVALUE';                         read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZVIDEOCPVISIBILITYSTATE';                  fex_col: 'ZVIDEOCPVISIBILITYSTATE';                       read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZVIDEOKEYFRAMETIMESCALE';                  fex_col: 'ZVIDEOKEYFRAMETIMESCALE';                       read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZVIDEOKEYFRAMEVALUE';                      fex_col: 'ZVIDEOKEYFRAMEVALUE';                           read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZVISIBILITYSTATE';                         fex_col: 'ZVISIBILITYSTATE';                              read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZWIDTH';                                   fex_col: 'ZWIDTH';                                        read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
//   (sql_col: 'DNT_ZYEARHIGHLIGHTBEINGKEYASSET';              fex_col: 'ZYEARHIGHLIGHTBEINGKEYASSET';                   read_as: ftString;        convert_as: '';           col_type: ftString;       show: True),
  );

begin
  if Name = 'PHOTOS_SQLITE_IOS' then Result := Array_Items_PHOTOS_SQLITE_IOS else
    Progress.Log(format('%-54s %-100s', ['Error: Did not locate artifact column layout:', Name]));
end;

end.
